-  user1:
    box-name: crossboxelfaro
    box-id: 10181
    email: your-email@example.com
    password: YourPasswordHere
    booking-goals:
      - monday,0730,Funcional
      - tuesday,0730,Funcional
      - wednesday,0730,Funcional
      - thursday,0730,Funcional
      - friday,0730,Funcional
    hours-in-advance: 24
    exceptions: {}

  